# Minimal overrides on top of default postgresql.conf, required for Debezium CDC.
listen_addresses = '*'
wal_level = logical            # bắt buộc để Debezium đọc WAL
max_wal_senders = 4
max_replication_slots = 4
